### ISSUE TITLE
결혼 준비 ToDo

### ISSUE THREAD

**Issue by heemang-minjung** [heemang-minjung/heemang-minjung.github.io#1]
# 식전 준비

- [ ] 식권 앞면 도장 or 싸인 표시
- [ ] 화환 최대 6개까지 가능 (부모님들께 사전에 말씀드리기)
- [ ] 혼인 서약서 만들기
- [ ] 성혼 선언문 만들기
- [ ] 사회자 대본 만들기
- [ ] 예배식 순서지 만들기
- [ ] 현악 3중주 선택하기
- [ ] 현악 3중주 리스트 엑셀파일 카카오톡 보내기 (러브클래식)
- [ ] 덕담이나 축사가 있으면 몇 명이 하는지 상의하기
- [ ] 플라워 샤워 진행 여부 (생화 8꼬깔서비스-지인 6-8명 직접섭외 요망)
- [ ] 액자 주문하기
- [ ] 식전 영상 만들기
- [ ] 축가 곡 정하기
- [ ] 서비스 선택하기 (웨팅카 등등...)
- [ ] 2주 전까지 이메일 보내기

# 이메일 리스트

- [ ] 혼인서약서
- [ ] 성혼선언문
- [ ] 사회자대본
- [ ] 예배 순서지
- [ ] 음원파일
- [ ] 식전영상 (식전, 식중 파일명 구분)
- [ ] 액자 갯수
- [ ] 축가 MR, 진행 인원
- [ ] 덕담, 축사 여부
- [ ] 성혼선언문 낭독 누가 하는지
- [ ] 플라워 샤워 진행여부
- [ ] 폐백 진행여부

**Comment by heemang-minjung** [comment]
[3중주리스트.xlsx](https://github.com/heemang-minjung/heemang-minjung.github.io/files/11050712/3.xlsx)
