### ISSUE TITLE
결혼식 당일 ToDo

### ISSUE THREAD

**Issue by heemang-minjung** [heemang-minjung/heemang-minjung.github.io#2]
- [ ] 신랑, 신부 1시간 30분 전까지 도착
- [ ] 직계가족 1시간 전까지 도착
- [ ] 신랑, 신부 예식장 도착 5분전 예약실로 전화 (02-2197-0230) 및 웨딩카 차량번호 말하기
- [ ] 축의금 받는 사람 예식시간 40분 전 도착 (예식시간 40분 전부터 접수대 세팅)
- [ ] 주례자, 사회자, 축가 예식시간 30분 전 도착
- [ ] 혼주 주차 6대, 6시간 무료 주차
